# Generated by Django 5.0 on 2024-08-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='location',
            new_name='branch',
        ),
    ]
