# Generated by Django 5.0 on 2024-10-19 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit contact number')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
